<a href="https://colab.research.google.com/github/silvererudite/ML_algos_onSomeDatasets/blob/master/Emg_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt
%matplotlib inline
#import seaborn as sns
plt.figure(figsize=(15,10))
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier

<Figure size 1080x720 with 0 Axes>

In [ ]:
data=pd.read_csv("feature_EMG.csv")

In [ ]:
data.head()

0      1       2       3  ...  Valence  Arousal  Dominance  Likings
0  23497.206583  402.0  4061.0  3461.0  ...        1        1          1        1
1  19498.338972   65.0  4069.0  2147.0  ...        1        1          1        1
2  20702.742997  168.0  4044.0  2238.0  ...        1        1          1        1
3  22017.146818  128.0  3980.0  2728.0  ...        0        1          1        1
4  24034.268091  243.0  4020.0  1965.0  ...        1        0          1        1

[5 rows x 30 columns]

In [ ]:
data.describe()

0            1  ...    Dominance      Likings
count    1280.000000  1280.000000  ...  1280.000000  1280.000000
mean    41770.126481   246.180469  ...     0.609375     0.664844
std     44191.816468   290.465727  ...     0.488081     0.472230
min     13568.818678     1.000000  ...     0.000000     0.000000
25%     21892.178299    72.000000  ...     0.000000     0.000000
50%     31314.785888   155.000000  ...     1.000000     1.000000
75%     44758.807922   300.500000  ...     1.000000     1.000000
max    720324.356522  3051.000000  ...     1.000000     1.000000

[8 rows x 30 columns]

In [ ]:
data.isnull().sum()

0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0
24           0
25           0
Valence      0
Arousal      0
Dominance    0
Likings      0
dtype: int64

In [ ]:
def knn_classifier():
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Valence'].values
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=7, leaf_size=3, p=1)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Classification report of valence")
    print(classification_report(y_test, y_predict))
    print("Accuracy score of Valence ")
    print(accuracy_score(y_test, y_predict)*100)
    
    
    
    ###############################################################################
    
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Arousal'].values
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=7)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Arousal ")
    print(accuracy_score(y_test, y_predict)*100)
    
    


In [ ]:
knn_classifier()

[[61 61]
 [53 81]]
Classification report of valence
              precision    recall  f1-score   support

           0       0.54      0.50      0.52       122
           1       0.57      0.60      0.59       134

    accuracy                           0.55       256
   macro avg       0.55      0.55      0.55       256
weighted avg       0.55      0.55      0.55       256

Accuracy score of Valence 
55.46875
[[ 42  58]
 [ 50 106]]
Accuracy score of Arousal 
57.8125


In [ ]:
def knn_classifier_pca():
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Valence'].values
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
       	
    # KNN classsifier
    clf = KNeighborsClassifier(n_neighbors=7, leaf_size=3, p=1)
    trained_model=clf.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )
    
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    
    print("Accuracy score of valence test KNN-PCA")
    
    print(accuracy_score(y_test, y_predict)*100)
    # print("AUC score for Valence")
    # print(roc_auc_score(y_test, y_predict))
    
    
    ########################################################################
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Arousal'].values
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=4)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
        
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
        	
    # KNN classsifier
    clf = KNeighborsClassifier(n_neighbors=9)
    trained_model=clf.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )
    
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    
    print("Accuracy score of Arousal test KNN-PCA")
    print(accuracy_score(y_test, y_predict)*100)

knn_classifier_pca()   
    

[[60 62]
 [43 91]]
Accuracy score of valence test KNN-PCA
58.984375
[[ 38  62]
 [ 49 107]]
Accuracy score of Arousal test KNN-PCA
56.640625


In [ ]:
def svm_classifier(): 
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Valence'].values
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # SVM Classifier
    clf = SVC(kernel = 'rbf', random_state = 42)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    
    print("Accuracy score of Valence ")
    print(accuracy_score(y_test, y_predict)*100)
    
    ###############################################################
    
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Arousal'].values
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # SVM Classifier
    clf = SVC(kernel = 'rbf', random_state = 42)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Arousal ")
    print(accuracy_score(y_test, y_predict)*100)
svm_classifier()

[[124 163]
 [105 248]]
Accuracy score of Valence 
58.12500000000001
[[ 17 259]
 [ 13 351]]
Accuracy score of Arousal 
57.49999999999999


In [ ]:
def svm_classifier_pca():
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Valence'].values
    print("Applying PCA to select features \n")
    
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
    #explained_variance=pca.explained_variance_ratio_
    
   
    print("Split the data into training/testing sets \n")

    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test_0 = train_test_split(X, y, test_size=0.33, random_state=4)
     
    
    print("Feature Scaling \n")
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    
    
    print("Applying SVM classifier \n")
    # SVM Classifier
    clf = SVC()
    clf.fit(X_train, y_train)
    y_predict_0 = clf.predict(X_test)
    cm = confusion_matrix(y_test_0, y_predict_0)
    print(cm)
    print("Accuracy score of Valence SVM-PCA")
    print(accuracy_score(y_test_0, y_predict_0)*100)
    
    #######################################################################
    
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Arousal'].values
    
    print("Applying PCA to select features \n")
    
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
    #explained_variance=pca.explained_variance_ratio_
    
   
    print("Split the data into training/testing sets \n")
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test_0 = train_test_split(X, y, test_size=0.33, random_state=4)
     
    
    print("Feature Scaling \n")
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    
    print("Applying SVM classifier \n")
    # SVM Classifier
    clf = SVC()
    clf.fit(X_train, y_train)
    y_predict_0 = clf.predict(X_test)
    cm = confusion_matrix(y_test_0,y_predict_0)
    print(cm)
    print(accuracy_score(y_test_0, y_predict_0)*100)
    
svm_classifier_pca()

Applying PCA to select features 

Split the data into training/testing sets 

Feature Scaling 

Applying SVM classifier 

[[ 67 121]
 [ 65 170]]
Accuracy score of Valence SVM-PCA
56.02836879432624
Applying PCA to select features 

Split the data into training/testing sets 

Feature Scaling 

Applying SVM classifier 

[[ 22 150]
 [ 32 219]]
56.973995271867615


In [ ]:
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# import time
# import matplotlib.pyplot as plt 
# from sklearn import model_selection
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.tree import DecisionTreeClassifier

# def cross_validate0():
    
#     # Get Data
#     X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
#     y=data['Valence'].values
    
   
    
#     # Split the data into training/testing sets
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
    
#      # Feature Scaling
#     from sklearn.preprocessing import StandardScaler
#     sc = StandardScaler()
#     X_train = sc.fit_transform(X_train)
#     X_test = sc.transform(X_test)
    
#      #principle component analysis
#     from sklearn.decomposition import PCA
#     pca = PCA(n_components=20)
#     X_train = pca.fit_transform(X_train)
#     X_test = pca.fit_transform(X_test)
    
   
    	
#     models = []
#     models.append(('LR', LogisticRegression(random_state = 0)))
#     models.append(('SVC', SVC(kernel = 'rbf', random_state = 0)))
     
#     models.append(('KNN', KNeighborsClassifier(n_neighbors=5)))
#     models.append(('DT', DecisionTreeClassifier(random_state = 0)))
    
#     scoring = 'accuracy'
    
#     # Cross Validate
#     results = []
#     names = []
#     timer = []
#     print('Model | Mean of CV | Std. Dev. of CV | Time')
#     for name, model in models:
#         start_time = time.time()
#         kfold = model_selection.KFold(n_splits=5, random_state=0)
#         cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
#         t = (time.time() - start_time)
#         timer.append(t)
#         results.append(cv_results)
#         names.append(name)
#         msg = "%s: %f (%f) %f s" % (name, cv_results.mean(), cv_results.std(), t)
#         print(msg)
    
        
#     models = []
#     for i in range(1,41): 
#         models.append(('KNN', KNeighborsClassifier(n_neighbors=i)))
#         results = []
#         names = []
#         timer = []
#         cv_knn = []
        
#         print('Model  | Mean of CV | Std. Dev. of CV | Time',i)
#         for name, model in models:
#             start_time = time.time()
#             kfold = model_selection.KFold(n_splits=4, random_state=42)
#             cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
#             t = (time.time() - start_time)
#             timer.append(t)
#             results.append(cv_results)
#             names.append(name)
#             msg = "%s: %f (%f) %f s" % (name, cv_results.mean(), cv_results.std(), t)
                
#             cv_knn.append(cv_results.mean())
#         print(msg)
        
#     print('\nmaximum accuracy for valence is',max(cv_knn))

    
#     plt.figure(figsize=(12, 6))  
#     plt.plot(range(1, 41), cv_knn, color='red', linestyle='dashed', marker='o',  
#              markerfacecolor='blue', markersize=10)
#     plt.title('mean cv_results of  K Value for Valence')  
#     plt.xlabel('K Value')  
#     plt.ylabel('Mean cv_result')  
    
        

# cross_validate0()

In [ ]:
def adaBoost_classifier(): 
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Valence'].values
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # SVM Classifier
    
    clf = AdaBoostClassifier(n_estimators=100, learning_rate=1, random_state=0)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    
    print("Accuracy score of Valence ")
    print(accuracy_score(y_test, y_predict)*100)
    
    ###############################################################
    
    X=data.drop(['Valence','Arousal','Dominance','Likings'],axis=1).values
    y=data['Arousal'].values
    # PCA to select features
    pca = PCA(n_components=20, svd_solver='full')
    pca.fit(X)
    X = pca.transform(X)
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # SVM Classifier
    clf = AdaBoostClassifier(n_estimators=100, learning_rate=1, random_state=0)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Arousal ")
    print(accuracy_score(y_test, y_predict)*100)

adaBoost_classifier()

[[50 60]
 [57 89]]
Accuracy score of Valence 
54.296875
[[40 67]
 [52 97]]
Accuracy score of Arousal 
53.515625
